language: python
python:
  - "2.7"
install:
  - ./bootstrap.py
script:
  - make jenkins
  - make harvest mediathread/main/features
  - make harvest mediathread/assetmgr/features
  - make harvest mediathread/projects/features